version: "3"

services:
  postgres:
    image: postgres:12
    restart: on-failure
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  migrate:
    image: luchenqun/blockscout:nelo
    depends_on:
      - postgres
    env_file:
      - config.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@192.168.0.59:5432/blockscout?ssl=false
    command: mix do ecto.create, ecto.migrate
  blockscout:
    image: luchenqun/blockscout:nelo
    depends_on:
      - postgres
    expose:
      - 4000
    ports:
      - 4000:4000
    env_file:
      - config.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@192.168.0.59:5432/blockscout?ssl=false
    command: mix phx.server

volumes:
  postgres-data-volume:
    external: true
